Repository TAVE-balak/OTTify-frontend, pull requests merged in 2024-01, with the labels that each got.

#19 Feature/#17 mypage participate
  src/App.js
  src/CSS/MyCollect.css
  src/CSS/MyDebate.css
  src/JS/DebateItem.js
  src/JS/DebateList.js
  src/JS/MyParticipate.js
  src/JS/Mypage.js
  src/img/chat.png
  src/img/debate_poster.png
Labels: 💫 feature

#20 Feature/#18 mypage mydebate
  src/App.js
  src/CSS/MyDebate.css
  src/JS/MyHost.js
  src/JS/Mypage.js
Labels: 💫 feature

#44 Feature/#43 page edit
  src/CSS/Mypage.css
  src/CSS/SlidePoster.css
  src/JS/DebateWrite.js
  src/JS/Mypage.js
  src/JS/SlidePoster.js
Labels: 💫 feature

#56 Setting: CI/CD 구축 (#55)
  .github/workflows/deploy.yml
  appspec.yml
  scripts/deploy.sh
Labels: 🗃️ infra

#57 Setting: CI/CD 구축 (#55)
  .github/workflows/deploy.yml
Labels: 🗃️ infra

#58 Setting: CI/CD 구축 (#55)
  .github/workflows/deploy.yml
Labels: 🗃️ infra

#59 Setting: CI/CD 구축 (#55)
  scripts/deploy.sh
Labels: 🗃️ infra

#68 Feature/#67 mainpage and programpage
  src/App.js
  src/CSS/MainPage.css
  src/JS/Mypage.js
  src/api/axios.js
  src/api/requests.js
  src/components/Login/Login.js
  src/components/MovieModal/Casts.js
  src/components/MovieModal/Otts.js
  src/components/MovieModal/index.js
  src/components/MovieModal/star.png
  src/components/Nav.js
  src/components/Row.css
  src/components/Row.js
  src/pages/MainPage/arrow_right.png
  src/pages/MainPage/index.js
Labels: 💫 feature, ♻️ refactor

#72 Feature/#67 mainpage and programpage
  src/CSS/MainPage.css
  src/CSS/Nav.css
  src/components/Login/Login.css
  src/components/Login/Login.js
  src/components/Login/naver.png
  src/components/MovieModal/Casts.css
  src/components/MovieModal/Casts.js
  src/components/Nav.js
  src/components/Row.css
  src/components/Row.js
  src/pages/MainPage/index.js
Labels: 💫 feature, ♻️ refactor

#76 Feature/#75 search page
  src/CSS/MainPage.css
  src/api/requests.js
  src/pages/MainPage/index.js
  src/pages/SearchPage/SearchPage.css
  src/pages/SearchPage/index.js
  src/pages/SearchPage/search_off.png
Labels: 💫 feature, ♻️ refactor

#80 Api/#79 detail page
  src/App.css
  src/App.js
  src/JS/AllReviewList.js
  src/JS/DebateOne.js
  src/components/MovieModal/DetailReview.css
  src/components/MovieModal/MovieModal.css
  src/components/MovieModal/MyCollect.css
  src/components/MovieModal/MyWrite.js
  src/components/MovieModal/ReviewItem.js
  src/components/MovieModal/ReviewList.js
  src/components/MovieModal/Toggle.js
  src/components/MovieModal/WriteReview.js
  src/components/MovieModal/hate_clicked.png
  src/components/MovieModal/heart.png
  src/components/MovieModal/heart_clicked.png
  src/components/MovieModal/index.js
  src/components/MovieModal/review.png
  src/pages/SearchPage/SearchPage.css
  src/pages/SearchPage/index.js
Labels: 💫 feature, ♻️ refactor

#85 Feature/#84 login
  src/App.js
  src/api/requests.js
  src/components/ChooseOtt.js
  src/components/Login/OnBoarding.js
  src/components/Pickbutton.js
  src/components/Preferences.js
Labels: 💫 feature
